Budget app
TamaraDimov/Budget-app pull request #1
Opened 2023-09-14 12:15 UTC by TamaraDimov

- [ ] Splash screen
-   A simple page with the name of your app (yes, you need to choose one), and links to the sign up and log in pages.
- [ ]  Sign up and log in pages
- The user should be able to register in the app with full name, email and password (all mandatory).
- The user can log into the app using email and password.
- If the user is not logged in, they can't access pages that require the user to be logged in (all the pages described below).
- [ ] Home page (categories page)
- When the user logs in, they are presented with the categories page.
- For each category, the user can see their name, icon and the total amount of all the transactions that belongs to that category.
- When the user clicks (or taps) on a category item, the application navigates to the transactions page for that category.
- There is a button "add a new category" at the bottom that brings the user to the page to create a new category.
- [ ]  Transactions page
- For a given category, the list of transactions is presented, ordered by the most recent.
- At the top of the page the user could see the total amount for the category (sum of all of the amounts of the transactions in that category).
- There is a button "add a new transaction" at the bottom that brings the user to the page to create a new transaction.
- When the user clicks on the "Back" button (<), the user navigates to the home page.
- [ ] "Add a new category" page
- The user fills out a form to create a new category, indicating their name and icon (both mandatory). 
- The user clicks (or taps) the "Save" button to create the new category, and is taken to the home page on success.
- When the user clicks on the "Back" button (<), the user navigates to the home page.
- [ ]  "Add a new transaction" page
- The user fills out a form to create a new transaction with:
- name (mandatory)
- amount (mandatory)
- categories (mandatory at least one)
- The user click (or taps) the "Save" button to create the new transaction, and is taken to the transactions page for that category.
- When the user clicks on the "Back" button (<), the user navigates to the transactions page for that category.

2023-09-14 15:49 UTC, cynthiainga requested changes
Hi @TamaraDimov, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights

- [ ] Use Postgres as the database for the application ✔️ 
- [ ] Use devise for authentication ✔️ 
- [ ] User can add new categories and transactions ✔️ 
- [ ] Correct Gitflow ✔️ 

## Required Changes ♻️

- [ ] As mentioned in the requirement you should add unit tests and integration tests, kindly add integration tests and controllers tests 🙃 🙃 
- [ ] Please kindly check the comments under the review 👇🏾 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-14 15:49 UTC, cynthiainga commented on README.md
> +
- [x] Good job so far but as mentioned in the project requirements the video should contain a highlight about a piece of the code that you find interesting or are proud of making 🙃 
- [x] Also you should deploy the application and add the live demo link to the README file 😁

2023-09-14 15:49 UTC, cynthiainga commented on README.md
> +
- [x] As mentioned in the requirements the README should contain an "Acknowledgements" section or similar that gives appropriate credit to [Gregoire Vella on Behance](https://www.behance.net/gregoirevella) the [author of the original design](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=), as required by the [Creative Commons license of the design](https://creativecommons.org/licenses/by-nc/4.0/), kindly add it 🙏🏾

2023-09-14 15:49 UTC, cynthiainga commented on app/views/users/index.html.erb
- [ ] Good job so far but you should make sure to follow the given design, as you can see in the original design the app title is in the center the login and sign buttons are on the bottom 🙃 

Your design

<img width="380" alt="Screenshot 2023-09-14 at 17 02 16" src="https://github.com/TamaraDimov/Budget-app/assets/74501523/8f2eb59f-28c0-4623-896b-b5a8dc69417b">

Original design

<img width="281" alt="Screenshot 2023-09-14 at 17 03 29" src="https://github.com/TamaraDimov/Budget-app/assets/74501523/98690565-f465-4aa7-a32c-26e4f8bb6949">

2023-09-14 15:49 UTC, cynthiainga commented on app/views/groups/index.html.erb
- [ ] Please kindly make sure to follow the design:
  - As you can see in the original design the picture design the icon should show but for your app, no matter what image you put in it won't display, kindly fix that 🙃 
  - The date should be displayed on the category page as well
  - I think it would be better if the logout button is placed on the right side
  - The principal title should be centered
  - The Add new category should have the same color as in the original design and the name of the category as well

Your design

<img width="512" alt="Screenshot 2023-09-14 at 17 23 53" src="https://github.com/TamaraDimov/Budget-app/assets/74501523/478a1e56-5ed0-4a9e-92f1-3b326bcf71c9">

Original design

<img width="409" alt="Screenshot 2023-09-14 at 17 24 47" src="https://github.com/TamaraDimov/Budget-app/assets/74501523/55daa85c-4213-44cd-bcd2-d68e224b6a98">

2023-09-14 15:49 UTC, cynthiainga commented on app/views/groups/show.html.erb
- [ ] Good so far but kindly follow the given design, it is very important to follow the given design 😁 
  - I think it would be better to put the Add a new transaction button to the bottom and style it like the Add new category button
  - Kindly center the principal title `group name` 
  - Also kindly make sure that there is no margin a the top

Your design

<img width="412" alt="Screenshot 2023-09-14 at 17 18 14" src="https://github.com/TamaraDimov/Budget-app/assets/74501523/44aba87d-a3d8-4405-973b-118a739c2c99">

Given design

<img width="409" alt="Screenshot 2023-09-14 at 18 26 06" src="https://github.com/TamaraDimov/Budget-app/assets/74501523/02e35798-9fbe-4005-9723-88d76e41ddb8">

2023-09-15 01:12 UTC, descholar-ceo approved these changes
Hi @TamaraDimov 🤝 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
👍🏽 Use Postgres as the database for the application ✔️
 👍🏽 Used devise for authentication ✔️
 👍🏽 User can add new categories and transactions ✔️
 👍🏽 Requested changes are implemented and there is no new issue introduced along the way✔️


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-15 07:57 UTC, merged